/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_chapter_4_2_2_opensl_OpenSLPlayer */

#ifndef _Included_com_flyscale_chapter_4_2_2_opensl_OpenSLPlayer
#define _Included_com_flyscale_chapter_4_2_2_opensl_OpenSLPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_chapter_4_2_2_opensl_OpenSLPlayer
 * Method:    getStringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_chapter_14_12_12_1opensl_OpenSLPlayer_getStringFromJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_flyscale_chapter_4_2_2_opensl_OpenSLPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_12_12_1opensl_OpenSLPlayer_play
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
